spring:
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    serialization:
      write-dates-as-timestamps: false
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
  data:
    mongodb:
      uri: mongodb+srv://${DB_MONGODB_USERNAME}:${DB_MONGODB_PASSWORD}@cluster0.7wqi5cz.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: ${DB_MONGODB_NAME}
      auto-index-creation: true
      max-connections-per-host: 100
      server-selection-timeout-ms: 30000
      connect-timeout-ms: 10000
      socket-timeout-ms: 30000
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: ${SENDGRID_API_KEY}
    properties:
      mail:
        smtp: 
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
      from: ${MAIL_FROM_ADDRESS:ngochuymail25@gmail.com}
      from-name: ${MAIL_FROM_NAME:TechShop E-commerce}
    default-encoding: UTF-8
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            redirect-uri: http://localhost:5173/oauth2/callback

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

api:
  prefix: api/v1

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    # Cấu hình cho production
    csrf:
      enabled: false
    # Cho phép Swagger UI hoạt động với HTTPS
    server-url: # Sẽ được auto-detect
  show-actuator: false
  packages-to-scan: com.example.e_commerce_techshop.controllers

jwt:
  secret: EQOIAUgMdB/GxPmYT+uew/HLvOkYDOrAo3ihcFynD+Y=
  expiration: 2592000
  expiration-refresh-token: 5184000 #60 days = 60 * 24 * 60 * 60

vnpay:
  pay-url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  return-url: "${VNPAY_RETURN_URI:http://localhost:5173/payments/payment-callback}"
  tmn-code: "${VNPAY_TMNCODE}"
  secret-key: "${VNPAY_SECRET_KEY}"
  api-url: "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"
